# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out the repo under $GITHUB_WORKSPACE
      - name: Checkout repo
        uses: actions/checkout@v2

      # Install deps
      - name: Install deps
        uses: bahmutov/npm-install@v1
      
      # Build with webpack
      - name: Build webpack
        run: npx webpack
      
      # Publish to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: $GITHUB_WORKSPACE
          github_token: ${{ secrets.GITHUB_TOKEN }}
